export {default as Nav} from './Nav'
export {default as Recent} from './Recent'
export {default as Episode} from './Episode'
export {default as Stream} from './Stream'
export {default as Search} from './Search'
export {default as Genre} from './Genre'
export {default as Genreanime} from './Genreanime'
export {default as Seasons} from './Seasons'